ci: Add ARM64 support
canonical/charm-sysconfig pull request #58
Opened 2024-08-15 03:11 UTC by jneo8

2024-08-15 04:42 UTC, samuelallan72 requested changes
Looks good thanks, just a suggestion for where to set the model constraints. :)

2024-08-15 04:42 UTC, samuelallan72 commented on src/tests/functional/conftest.py
> +    await model.set_constraints(constraints=get_constraints())
I think this should be set when the model is created, in `model()`, before yielding the model.  This will ensure that the model constraints will be always set.

2024-08-15 06:46 UTC, samuelallan72 submitted a review, later dismissed
Thanks, looks good

2024-08-16 05:58 UTC, chanchiwai-ray requested changes

2024-08-16 05:58 UTC, chanchiwai-ray commented on charmcraft.yaml
> +          - amd64
they should be `arm64`

2024-08-16 06:30 UTC, samuelallan72 commented on src/tests/functional/test_deploy.py
> +    RETRY(await verify_systemd_content())
huh I've never seen this before - how does it work?  Why doesn't the `await func()` resolve before `RETRY()` is called?  How does `RETRY()` get a reference to that awaited function so it can retry it?  :thinking:

2024-08-16 06:49 UTC, jneo8 commented on src/tests/functional/test_deploy.py
> +    RETRY(await verify_systemd_content())
Because it can retry on coroutines?

https://tenacity.readthedocs.io/en/latest/#async-and-retry

2024-08-16 06:51 UTC, samuelallan72 commented on src/tests/functional/test_deploy.py
> +    RETRY(await verify_systemd_content())
This is quite different though - this isn't wrapping a function definition in the retry decorator, this is wrapping the function call itself. :thinking:

2024-08-16 06:53 UTC, samuelallan72 approved these changes
LGTM :)

2024-08-16 07:32 UTC, rgildein commented on src/tox.ini
> +commands = pytest {toxinidir}/tests/functional -vvvv
It's really useful to be able to change parameters, e.g. `-k test_config_changed`.
```suggestion
commands = pytest {toxinidir}/tests/functional {posargs:-vvvv}
```

2024-08-16 09:53 UTC, chanchiwai-ray approved these changes

2024-08-18 23:33 UTC, samuelallan72 approved these changes

2024-08-19 01:41 UTC, merged